---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
  templates:
  - post
- type: heading
  label: Options
- type: document
  path: data/locations
  label: Locations
- type: document
  path: data/categories.yaml
  label: Categories
- type: document
  path: data/organization.yaml
  label: Organization
upload_dir: ''
public_path: https://res.cloudinary.com/verdeco/image/upload/c_scale,w_640
front_matter_path: https://res.cloudinary.com/verdeco/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.2
